name: sellatrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  go_router: ^15.1.2
  dartz: ^0.10.1
  talker_flutter: ^4.7.6
  talker_riverpod_logger: ^4.7.6
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
