// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk_HBUrflYCJldgsVzrQWQp7Rxpw6DGj8',
    appId: '1:561909823794:web:03c4bc744c6ff2646cbf2b',
    messagingSenderId: '561909823794',
    projectId: 'sellatrack',
    authDomain: 'sellatrack.firebaseapp.com',
    storageBucket: 'sellatrack.firebasestorage.app',
    measurementId: 'G-568KZBNZSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUmdX8pTApibJ_u2bpAleIWeUmSvbUNVA',
    appId: '1:561909823794:android:53dd1f51f42419496cbf2b',
    messagingSenderId: '561909823794',
    projectId: 'sellatrack',
    storageBucket: 'sellatrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGjdEscLKGpvE6nx5rh19lit_hiyYBBHs',
    appId: '1:561909823794:ios:14ce0f1dca00a55d6cbf2b',
    messagingSenderId: '561909823794',
    projectId: 'sellatrack',
    storageBucket: 'sellatrack.firebasestorage.app',
    iosBundleId: 'com.example.sellatrack',
  );
}
